[tools]
rojo = { source = "rojo-rbx/rojo", version = "6.2.0" }
selene = { source = "kampfkarren/selene", version = "0.13.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.10.0" }
wally = { source = "UpliftGames/wally", version = "0.1.1" }
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3.0" }
